services:
- docker

env:
  global:
  - secure: iC7ke9HBF0xbcbKGpiAbVLsRsHyCs4DmLCsuKSJlPMEwviJqWfnLGWQ/iFDRJPXYGJUjJXKD08/fkZ3KUcXzasyN34EGmfLUQPS+n5B31SGpC25cTiiLbIbO2HirfokzCcheXw8shZcqnDWGL+AXujsmSVkkN3iRxiIXw3TEGSVjttGebYRywD6ROjxlKTE0m0vZnQ1V0jtER7ZbzraO/I6+CCljicbFMvJWBxgHJAxx7hHf9B9cNnhsoGDxo/WimGvi5DoZp3X0RRp2fJVENseZfxEhdvlEBoWVGNzg74u2MltbDA+g+yQXVq8o6ZT06r9/PeOY3WrWXJos02WJBbDaDS9pfty4ub8rZzWjB3SP6wvksF9JIDc3i9BE6IunmkV1UxEOYHkb3YiGNIe2BNIkwdR8PLYl8PEZ2AwDeu2fD5kqeuzn2l2SCswVm5GS9XsWGqSubTRXXUfMyfPURtC6BPBCiAj43JLc/yd6O5hFK9ZIn5aQN3nqm0jRA1Q4atKYkNHF17CmgQslZWU3rN0yU98UAWSoopJfkE94bPOH+Fc8/DJKeO2zGk6GtVY9GnI4kmJwdXLBG1zJWTehBwURFyXGyAbNBBgRwcbJEfAa3IbT1s3V457+9fGctfYDNQcjbCOt2Il6DiMlWWQ3KoPFbP3vjgWXKuj4k5c614g=
  - secure: X7QXSx3eiUdK4xcht0pOyzoZhwhWAYxwsAvDvZzTF7ea3OIpuJTyBe8TUZ2/ZXd05V9Sk0Uv9kqd37wBassEgyO76BfwrFt5vbkZheTvRrj/1os5cYtgPvNX/VYFvY9/L+mjnIssWHCVe7znSDlGsFrHEYKc76fBbpUrt91zm6mUeLgZpQuy4jnsndmfFKsN/ffySRum7gVYJLZ+srIoStby9NqJ3U92Tq3a8WX1d5UtfdYO8lHDLANsmO7gtfChAl3WYuRBzLaX9PlsrvuMrWO7nifCI4NkjfM3OhU+HGdOKIZQYIG1cJSxzXner0zYW1MWGFJvQigOPccS+ZWfzznPrWSDeCRKVkGT340H8BIRtCDTu7nxWDSfQXY9aaxnbpHZAlXUVp0qOt5G917sE1tUgo2+DceDFpGxyHLpz9KMAo/TMatNK/zeDLbuollYOw5X79YT2Q+fNHDlrsIO4+wfXgGQdNfrIuh3x6xc/IlJIMTscLLqTnQym0/AkE2MReF7/5qZiB170LSlOni0ilAc8wpTgMTkIZ6r90w8OJ7A7gpqJju473CnrmvNhHoRycUmQ3vW6ZUFLwVK7JkcwWclm8JKYCfqfqmHAU+M4p8eU25mBNH2HgJs3B8y1bYLU8/mi1b6wS6t7SpHVoTq7IQz9F+3URpHNlqEMLwPqyw=

script:
- docker build -t opennode/waldur-mastermind .

after_script:
- docker images

before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "opennode/waldur-mastermind:latest"
  on:
    branch: master
